version: '3.3'
services:
  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: teacea/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/django/
      - media_value:/app/media/django/
      - redoc:/app/docs/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: teacea/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/
      - static_value:/var/html/static/django
      - media_value:/var/html/media/django
    depends_on:
      - backend
volumes:
  postgres_data:
  static_value:
  media_value: 
  redoc: